# Remarque: avant de lancer docker-compose up, il faut régler le fichier .env
# en partant du fichier .env-dist qui donne les variables d'environnements
# à personnaliser et des exemples de valeurs.
#

version: "3.5"

services:

#######################################
# theses-api-recherche
# API de recherche de theses.fr
  theses-api-recherche:
    container_name: ws-mail
    image: abesesr/wsmail:${WSMAIL_VERSION}
    restart: unless-stopped
    mem_limit: ${MEM_LIMIT}
    memswap_limit: ${MEM_LIMIT}
    cpus: ${CPU_LIMIT}
    ports:
      - ${WSMAIL_HTTP_PORT}:8990
    environment:
      #DEFAUT
      SPRING_MAIL_PORT: ${WSMAIL_SPRING_MAIL_PORT}
      SPRING_MAIL_HOST: ${WSMAIL_SPRING_MAIL_HOST}
      SPRING_MAIL_USERNAME: ${WSMAIL_SPRING_MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${WSMAIL_SPRING_MAIL_PASSWORD}
      SPRING_MAIL_SENDER: ${WSMAIL_SPRING_MAIL_SENDER}
      #WEBSTATS
      WEBSTATS_MAIL_HOST: ${WSMAIL_WEBSTATS_MAIL_HOST}
      WEBSTATS_MAIL_USERNAME: ${WSMAIL_WEBSTATS_MAIL_USERNAME}
      WEBSTATS_MAIL_PASSWORD: ${WSMAIL_WEBSTATS_MAIL_PASSWORD}
      WEBSTATS_MAIL_SENDER: ${WSMAIL_WEBSTATS_MAIL_SENDER}
      #CIDEMIS
      CIDEMIS_MAIL_HOST: ${WSMAIL_CIDEMIS_MAIL_HOST}
      CIDEMIS_MAIL_USERNAME: ${WSMAIL_CIDEMIS_MAIL_USERNAME}
      CIDEMIS_MAIL_PASSWORD: ${WSMAIL_CIDEMIS_MAIL_PASSWORD}
      CIDEMIS_MAIL_SENDER: ${WSMAIL_CIDEMIS_MAIL_SENDER}
      #LN
      LN_MAIL_HOST: ${WSMAIL_LN_MAIL_HOST}
      LN_MAIL_USERNAME: ${WSMAIL_LN_MAIL_USERNAME}
      LN_MAIL_PASSWORD: ${WSMAIL_LN_MAIL_PASSWORD}
      LN_MAIL_SENDER: ${WSMAIL_LN_MAIL_SENDER}
      #ITEM
      ITEM_MAIL_HOST: ${WSMAIL_ITEM_MAIL_HOST}
      ITEM_MAIL_USERNAME: ${WSMAIL_ITEM_MAIL_USERNAME}
      ITEM_MAIL_PASSWORD: ${WSMAIL_ITEM_MAIL_PASSWORD}
      ITEM_MAIL_SENDER: ${WSMAIL_ITEM_MAIL_SENDER}
      #CONVERGENCE
      CONVERGENCE_MAIL_HOST: ${WSMAIL_CONVERGENCE_MAIL_HOST}
      CONVERGENCE_MAIL_USERNAME: ${WSMAIL_CONVERGENCE_MAIL_USERNAME}
      CONVERGENCE_MAIL_PASSWORD: ${WSMAIL_CONVERGENCE_MAIL_PASSWORD}
      CONVERGENCE_MAIL_SENDER: ${WSMAIL_CONVERGENCE_MAIL_SENDER}

    labels:
      # pour envoyer les logs dans le puits de log de l'abes
      - "co.elastic.logs/enabled=true"
      - "co.elastic.logs/processors.add_fields.target="
      - "co.elastic.logs/processors.add_fields.fields.abes_appli=wsmail"
      - "co.elastic.logs/processors.add_fields.fields.abes_middleware=spring"
      # pour que les mises à jour de cette image soient auto-déployées par watchtower
      - "com.centurylinklabs.watchtower.scope=wsmail-watchtower-scope"
